import { Programme } from '@/types'

export const programmes: Programme[] = [
  {
    slug: 'web2-launchpad',
    name: 'Web2 Launchpad',
    type: 'track',
    tagline: 'Zero to web developer in 12 weeks',
    description: 'Built for complete beginners with no prior coding experience. You will learn HTML, CSS, and JavaScript from the ground up, building real projects every week until you can confidently call yourself a web developer.',
    duration: '12 weeks',
    format: 'Remote',
    level: 'Beginner',
    weeks: 12,
    icon: 'layout',
    color: '#185FA5',
    fee: { ngn: 150000, usd: 100 },
    prerequisites: ['No experience needed', 'A laptop and stable internet connection', 'Commitment to 20+ hours per week'],
    outcomes: [
      'Build and deploy static websites from scratch',
      'Write clean, semantic HTML and CSS',
      'Add interactivity with JavaScript',
      'Use Git and GitHub for version control',
      'Deploy projects to Netlify',
    ],
    curriculum: [
      { week: 'Week 1–2', title: 'HTML Foundations', topics: ['Document structure', 'Semantic HTML', 'Forms and inputs', 'Accessibility basics'] },
      { week: 'Week 3–4', title: 'CSS Styling', topics: ['Selectors and specificity', 'Box model', 'Flexbox', 'CSS Grid', 'Responsive design'] },
      { week: 'Week 5–6', title: 'JavaScript Basics', topics: ['Variables and data types', 'Functions', 'DOM manipulation', 'Events'] },
      { week: 'Week 7–8', title: 'JavaScript Intermediate', topics: ['Arrays and objects', 'Loops and conditionals', 'Fetch API', 'Async/await basics'] },
      { week: 'Week 9–10', title: 'Git and Deployment', topics: ['Git version control', 'GitHub', 'Netlify deployment', 'Project collaboration'] },
      { week: 'Week 11–12', title: 'Final Project', topics: ['Full website build', 'Code review', 'Project presentation', 'Career prep'] },
    ],
  },
  {
    slug: 'advanced-frontend',
    name: 'Advanced Frontend',
    type: 'track',
    tagline: 'Production-grade interfaces with React and Node.js',
    description: 'For developers who already know HTML, CSS, and JavaScript. This track takes you deep into modern frontend engineering — advanced JavaScript patterns, React, Node.js, and the tools used by professional engineers.',
    duration: '12 weeks',
    format: 'Remote',
    level: 'Intermediate',
    weeks: 12,
    icon: 'code',
    color: '#0E5A8C',
    fee: { ngn: 200000, usd: 130 },
    prerequisites: ['Solid HTML, CSS, and JavaScript knowledge', 'Completed Web2 Launchpad or equivalent', 'Familiarity with Git'],
    outcomes: [
      'Build complex React applications',
      'Work with Node.js and Express',
      'Manage application state effectively',
      'Write and consume REST APIs',
      'Deploy full-stack applications',
    ],
    curriculum: [
      { week: 'Week 1–2', title: 'Advanced JavaScript', topics: ['ES6+ features', 'Closures and scope', 'Promises and async', 'Functional programming'] },
      { week: 'Week 3–5', title: 'React', topics: ['Components and props', 'State and hooks', 'Context API', 'React Router', 'Performance optimisation'] },
      { week: 'Week 6–7', title: 'Node.js and Express', topics: ['Server setup', 'REST API design', 'Middleware', 'Authentication'] },
      { week: 'Week 8–9', title: 'TypeScript', topics: ['Type system basics', 'Interfaces and generics', 'TypeScript with React', 'Error handling'] },
      { week: 'Week 10–11', title: 'Testing and tooling', topics: ['Unit testing with Jest', 'Integration testing', 'CI/CD basics', 'Code review'] },
      { week: 'Week 12', title: 'Capstone project', topics: ['Full-stack app build', 'Deployment', 'Portfolio presentation'] },
    ],
  },
  {
    slug: 'backend-engineering',
    name: 'Backend Engineering',
    type: 'track',
    tagline: 'APIs, databases, and server infrastructure with Python',
    description: 'Learn to build the invisible engine that powers web applications. Python-based backend development covering REST APIs, databases, authentication, and cloud deployment — everything that happens behind the screen.',
    duration: '12 weeks',
    format: 'Remote',
    level: 'Intermediate',
    weeks: 12,
    icon: 'server',
    color: '#376E0F',
    fee: { ngn: 200000, usd: 130 },
    prerequisites: ['Basic programming knowledge', 'Some web development experience helpful', 'Familiarity with how the web works'],
    outcomes: [
      'Build production-ready REST APIs with Python',
      'Design and query relational databases',
      'Implement secure authentication systems',
      'Deploy backend services to the cloud',
      'Write tests for backend code',
    ],
    curriculum: [
      { week: 'Week 1–2', title: 'Python fundamentals', topics: ['Syntax and data types', 'Functions and modules', 'File handling', 'OOP basics'] },
      { week: 'Week 3–4', title: 'Web frameworks', topics: ['FastAPI or Django', 'Routing and views', 'Request/response cycle', 'Middleware'] },
      { week: 'Week 5–6', title: 'Databases', topics: ['SQL fundamentals', 'PostgreSQL', 'ORMs', 'Database design and migrations'] },
      { week: 'Week 7–8', title: 'Authentication and security', topics: ['JWT tokens', 'OAuth', 'Password hashing', 'CORS and rate limiting'] },
      { week: 'Week 9–10', title: 'Cloud and DevOps', topics: ['Docker basics', 'Environment variables', 'Deployment on Railway/Render', 'Monitoring'] },
      { week: 'Week 11–12', title: 'Final API project', topics: ['Full API build', 'Documentation with Swagger', 'Testing', 'Presentation'] },
    ],
  },
  {
    slug: 'web3-engineering',
    name: 'Web3 Engineering',
    type: 'track',
    tagline: 'Build and deploy smart contracts and dApps to mainnet',
    description: "Africa's flagship blockchain engineering programme. 16 intensive weeks of Solidity, Hardhat, Foundry, EtherJS, and decentralised application development. You will ship real products to mainnet before you graduate.",
    duration: '16 weeks',
    format: 'Onsite + Remote',
    level: 'Intermediate',
    weeks: 16,
    icon: 'cube',
    color: '#E63946',
    fee: { ngn: 350000, usd: 230 },
    prerequisites: ['Solid JavaScript or Python knowledge', 'Basic understanding of how blockchains work', 'Completed Web2 Launchpad or equivalent preferred'],
    outcomes: [
      'Write and audit Solidity smart contracts',
      'Use Hardhat and Foundry for development and testing',
      'Build frontend dApps with EtherJS and Wagmi',
      'Deploy contracts to Ethereum mainnet and L2s',
      'Understand DeFi primitives and token standards',
    ],
    curriculum: [
      { week: 'Week 1–2', title: 'Blockchain fundamentals', topics: ['How Ethereum works', 'Wallets and keys', 'Transactions and gas', 'EVM architecture'] },
      { week: 'Week 3–5', title: 'Solidity basics', topics: ['Variables and types', 'Functions and visibility', 'Events and errors', 'Mappings and arrays'] },
      { week: 'Week 6–8', title: 'Smart contract patterns', topics: ['ERC-20 and ERC-721', 'Access control', 'Upgradeable contracts', 'Security patterns'] },
      { week: 'Week 9–10', title: 'Development tools', topics: ['Hardhat setup', 'Foundry', 'Testing smart contracts', 'Contract verification'] },
      { week: 'Week 11–12', title: 'Frontend integration', topics: ['EtherJS', 'Wagmi and RainbowKit', 'Connecting wallets', 'Reading contract state'] },
      { week: 'Week 13–14', title: 'DeFi and advanced topics', topics: ['Uniswap mechanics', 'Lending protocols', 'Flash loans', 'MEV basics'] },
      { week: 'Week 15–16', title: 'Final dApp project', topics: ['Full dApp build', 'Mainnet deployment', 'Audit exercise', 'Demo day'] },
    ],
  },
  {
    slug: 'rust-engineering',
    name: 'Rust Engineering',
    type: 'track',
    tagline: 'Systems programming and blockchain protocol development',
    description: 'Three phases of deep systems programming in Rust — from language fundamentals to building performant, memory-safe blockchain infrastructure. For engineers who want to work at the protocol layer.',
    duration: '16 weeks',
    format: 'Remote',
    level: 'Advanced',
    weeks: 16,
    icon: 'bolt',
    color: '#B45A0A',
    fee: { ngn: 350000, usd: 230 },
    prerequisites: ['Strong programming background in any language', 'Comfortable with low-level concepts', 'Prior experience with compiled languages helpful'],
    outcomes: [
      'Write safe, performant Rust code',
      'Understand ownership, borrowing, and lifetimes',
      'Build CLI tools and backend services in Rust',
      'Work on blockchain node implementations',
      'Contribute to Rust-based blockchain projects',
    ],
    curriculum: [
      { week: 'Phase 1 (Wk 1–5)', title: 'Rust fundamentals', topics: ['Ownership and borrowing', 'Structs and enums', 'Pattern matching', 'Error handling', 'Traits and generics'] },
      { week: 'Phase 2 (Wk 6–11)', title: 'Systems programming', topics: ['Concurrency', 'Async Rust with Tokio', 'File I/O', 'Networking', 'CLI applications'] },
      { week: 'Phase 3 (Wk 12–16)', title: 'Blockchain with Rust', topics: ['Substrate basics', 'Solana program development', 'P2P networking', 'Cryptographic primitives', 'Final project'] },
    ],
  },
  {
    slug: 'zero-knowledge-proofs',
    name: 'Zero Knowledge Proofs',
    type: 'track',
    tagline: 'Cryptography, circuits, and privacy protocols at the frontier',
    description: 'Six phases of ZK cryptography for engineers who want to work at the absolute frontier of blockchain technology. Mathematical foundations, circuit design, ZK protocols, and real privacy applications.',
    duration: '16 weeks',
    format: 'Remote',
    level: 'Advanced',
    weeks: 16,
    icon: 'lock',
    color: '#0F6E56',
    fee: { ngn: 350000, usd: 230 },
    prerequisites: ['Strong mathematics background', 'Solid programming experience', 'Prior blockchain engineering experience preferred', 'Familiarity with cryptographic concepts'],
    outcomes: [
      'Understand the mathematics behind ZK proofs',
      'Design and implement ZK circuits',
      'Work with Circom and SnarkJS',
      'Build privacy-preserving applications',
      'Contribute to ZK protocol development',
    ],
    curriculum: [
      { week: 'Phase 1 (Wk 1–2)', title: 'Mathematical foundations', topics: ['Number theory', 'Elliptic curves', 'Polynomial commitments', 'Hash functions'] },
      { week: 'Phase 2 (Wk 3–4)', title: 'ZK proof systems', topics: ['SNARKs and STARKs', 'Groth16', 'PLONK', 'Proof generation and verification'] },
      { week: 'Phase 3 (Wk 5–8)', title: 'Circuit design', topics: ['Circom language', 'Constraint systems', 'Signal types', 'Circuit optimisation'] },
      { week: 'Phase 4 (Wk 9–11)', title: 'ZK applications', topics: ['Private transactions', 'Identity systems', 'zkRollups', 'ZK-EVM concepts'] },
      { week: 'Phase 5 (Wk 12–14)', title: 'Advanced protocols', topics: ['Recursive proofs', 'Nova and Halo2', 'Folding schemes', 'Proof aggregation'] },
      { week: 'Phase 6 (Wk 15–16)', title: 'Research project', topics: ['Original ZK application', 'Paper writeup', 'Peer review', 'Presentation'] },
    ],
  },
  // SPRINTS
  {
    slug: 'ui-ux-design',
    name: 'UI/UX Design',
    type: 'sprint',
    tagline: 'Design products people enjoy using',
    description: 'A focused 4-week sprint covering the full design process — from user research to Figma prototypes. Learn to think like a designer, build a portfolio-worthy project, and work effectively with engineering teams.',
    duration: '4 weeks',
    format: 'Remote',
    level: 'Beginner',
    weeks: 4,
    icon: 'vector',
    color: '#993578',
    fee: { ngn: 50000, usd: 35 },
    prerequisites: ['No design experience needed', 'A laptop with internet access'],
    outcomes: [
      'Conduct user research and interviews',
      'Create wireframes and prototypes in Figma',
      'Apply design systems and component libraries',
      'Present and defend design decisions',
    ],
    curriculum: [
      { week: 'Week 1', title: 'Design thinking and research', topics: ['User research methods', 'Personas', 'Problem framing', 'Competitive analysis'] },
      { week: 'Week 2', title: 'Wireframing and IA', topics: ['Information architecture', 'Low-fidelity wireframes', 'User flows', 'Feedback loops'] },
      { week: 'Week 3', title: 'Figma and prototyping', topics: ['Figma fundamentals', 'Design systems', 'High-fidelity designs', 'Interactive prototypes'] },
      { week: 'Week 4', title: 'Handoff and presentation', topics: ['Developer handoff', 'Design specs', 'Portfolio project', 'Final presentation'] },
    ],
  },
  {
    slug: 'product-management',
    name: 'Product Management',
    type: 'sprint',
    tagline: 'Strategy, roadmapping, and shipping great products',
    description: 'Learn how to define, prioritise, and ship great products. This 4-week sprint covers everything from writing user stories to working with engineering and design teams, with a focus on tech products in African markets.',
    duration: '4 weeks',
    format: 'Remote',
    level: 'Beginner',
    weeks: 4,
    icon: 'chart',
    color: '#507A0A',
    fee: { ngn: 50000, usd: 35 },
    prerequisites: ['No PM experience needed', 'Curiosity about how products are built'],
    outcomes: [
      'Write clear product requirements and user stories',
      'Build and prioritise a product roadmap',
      'Work effectively with engineering and design',
      'Conduct user interviews and analyse data',
    ],
    curriculum: [
      { week: 'Week 1', title: 'Product fundamentals', topics: ['What PMs do', 'Product discovery', 'User research', 'Problem definition'] },
      { week: 'Week 2', title: 'Roadmapping and prioritisation', topics: ['OKRs', 'Prioritisation frameworks', 'Roadmap building', 'Stakeholder alignment'] },
      { week: 'Week 3', title: 'Execution', topics: ['Writing PRDs', 'User stories', 'Sprint planning', 'Working with engineers'] },
      { week: 'Week 4', title: 'Launch and metrics', topics: ['Go-to-market', 'KPIs and analytics', 'Post-launch iteration', 'PM portfolio'] },
    ],
  },
  {
    slug: 'web3-intro',
    name: 'Web3 Intro',
    type: 'sprint',
    tagline: 'Understand the decentralised web — no code required',
    description: 'A 3-week introduction to blockchain technology, DeFi, NFTs, and Web3 for non-developers. Understand how the decentralised web works, why it matters, and how to navigate it confidently.',
    duration: '3 weeks',
    format: 'Remote',
    level: 'Beginner',
    weeks: 3,
    icon: 'globe',
    color: '#E63946',
    fee: { ngn: 30000, usd: 20 },
    prerequisites: ['No technical experience needed', 'Curiosity about blockchain and Web3'],
    outcomes: [
      'Understand how blockchains and Ethereum work',
      'Set up and use a crypto wallet',
      'Navigate DeFi protocols safely',
      'Understand NFTs and digital ownership',
    ],
    curriculum: [
      { week: 'Week 1', title: 'Blockchain basics', topics: ['What is a blockchain', 'Bitcoin and Ethereum', 'Wallets and keys', 'Transactions and fees'] },
      { week: 'Week 2', title: 'DeFi and tokens', topics: ['What is DeFi', 'DEXes and AMMs', 'Stablecoins', 'Yield and risks'] },
      { week: 'Week 3', title: 'NFTs and the ecosystem', topics: ['NFT standards', 'Marketplaces', 'DAOs', 'Web3 careers and opportunities'] },
    ],
  },
  {
    slug: 'ai-for-beginners',
    name: 'AI for Beginners',
    type: 'sprint',
    tagline: 'Understand AI, master prompting, build your first app',
    description: 'A practical 3-week sprint for anyone who wants to understand and use AI tools effectively. Learn how language models work, master prompt engineering, and build a simple AI-powered application — no coding experience required.',
    duration: '3 weeks',
    format: 'Remote',
    level: 'Beginner',
    weeks: 3,
    icon: 'brain',
    color: '#185FA5',
    fee: { ngn: 30000, usd: 20 },
    prerequisites: ['No AI or coding experience needed', 'A laptop and internet connection'],
    outcomes: [
      'Understand how large language models work',
      'Write effective prompts for any AI tool',
      'Use AI to 10x your productivity',
      'Build a simple AI-powered app with no-code tools',
    ],
    curriculum: [
      { week: 'Week 1', title: 'How AI works', topics: ['What are LLMs', 'Training and fine-tuning', 'Capabilities and limitations', 'AI tools landscape'] },
      { week: 'Week 2', title: 'Prompt engineering', topics: ['Prompt patterns', 'Chain of thought', 'Few-shot examples', 'System prompts'] },
      { week: 'Week 3', title: 'Building with AI', topics: ['No-code AI tools', 'AI APIs basics', 'Building a simple chatbot', 'AI project showcase'] },
    ],
  },
]

export const getProgramme = (slug: string) => programmes.find(p => p.slug === slug)
export const getTracks = () => programmes.filter(p => p.type === 'track')
export const getSprints = () => programmes.filter(p => p.type === 'sprint')
